version: "3"

services:
  live_app:
    build: .
    env_file:
      - .env
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "80:80"
    depends_on:
      - live_app
volumes:
  static_vol:
  media_vol:
