# Generated by Django 4.1.7 on 2024-07-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_rename_maintenance_hostel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='issues_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('successful', 'successful')], default='pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='tranfar_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('successful', 'successful')], default='pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='request_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('successful', 'successful')], default='pending', max_length=255, null=True),
        ),
    ]
