# Generated by Django 4.1.7 on 2024-07-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostel_issues_status_hostel_tranfar_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='request',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='request_status',
        ),
        migrations.CreateModel(
            name='Transfar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfar', models.CharField(blank=True, max_length=255, null=True)),
                ('transfar_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('successful', 'successful')], default='pending', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfar', to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=255, null=True)),
                ('request_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('successful', 'successful')], default='pending', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='hostel.hostel')),
            ],
        ),
    ]
